name: mdc_web_example
description: Example usage of the mdc_web package.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
 mdc_web:
   path: ../

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  sass_builder:
    # This is a temporary work around to have sass_builder include node_modules
    # when it looks for .scss files. The workaround will no longer be needed
    # when https://github.com/dart-league/sass_builder/pull/47 is released.
    git: https://github.com/jifalops/sass_builder
