name: mdc_web
description: Dart wrapper for the material-components-web javascript library.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jacob Phillips <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  test: ^1.3.4