name: mdc_web
description: Dart wrapper for the material-components-web javascript library.
version: 0.4.0
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/mdc_web

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0