name: mdc_web_example_demo
description: Example usage of the mdc_web package.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
 mdc_web:
   path: ../..

dev_dependencies:
  sass_builder: ^2.1.0
  build_runner: ^1.6.0
  build_web_compilers: ^2.2.0
