name: mdc_web_example_themes
description: Example usage of the mdc_web package.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
 mdc_web:
   path: ../..

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  js: any
  sass_builder: any

